### ISSUE TITLE
ansible.builtin.git fails to clone auth uvs

### ISSUE THREAD

**Issue by teapot9** [mother-of-all-self-hosting/ansible-role-jitsi#37]
In `tasks/util/setup_jitsi_auth_uvs_install.ym`, we have the following:

```yaml
- name: Checkout Prosody Auth Matrix User Verification Plugin Repo
  ansible.builtin.git:
    repo: "{{ jitsi_prosody_auth_matrix_user_verification_repo_location }}"
    dest: "{{ jitsi_prosody_auth_matrix_user_verification_repo_target }}"
    version: "{{ jitsi_prosody_auth_matrix_user_verification_repo_version }}"
  become: true
  become_user: "{{ jitsi_user_username }}"
```

However, the variable used as `dest` defaults to (see `defaults/main.yml`):

```yaml
jitsi_prosody_auth_matrix_user_verification_repo_target:
  - "{{ jitsi_prosody_ext_path }}/prosody_auth_matrix_user_verification"
```

`ansible.builtin.git` fails for me, and I believe this is because it doesn't expect the `dest` argument to be a list.
It looks like this change is recent from commit 3b6c870ea59661496338a0472051eb513c137940.
